name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish for Windows
      run: dotnet publish CryptoInvest/CryptoInvest.csproj -c Release -o win-x64 --runtime win-x64 --self-contained true -p:PublishSingleFile=true -p:DebugType=None -p:DebugSymbols=false
    - name: Publish for Linux
      run: dotnet publish CryptoInvest/CryptoInvest.csproj -c Release -o linux-x64 --runtime linux-x64 --self-contained true -p:PublishSingleFile=true -p:DebugType=None -p:DebugSymbols=false
    - name: Archive Windows
      uses: actions/upload-artifact@v2
      with:
        name: win-x64
        path: win-x64
    - name: Archive Linux
      uses: actions/upload-artifact@v2
      with:
        name: linux-x64
        path: linux-x64
